project:
  type: website
  output-dir: docs

website:
  title: "ECONS-307"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.html
        text: Séance d'introduction