project:
  type: website
  output-dir: docs

website:
  title: "ECONS-307"
  navbar:
    left:
      - href: slides/index.html
        text: Séance d'introduction
      - href: R_intro/intro_R.html
        text: Introduction à R