---
title: "Séminaire d'économie appliquée - Partie Prix"
format: html
---

La plateforme présente a pour objectif d'accompagner les étudiant$\cdot$es dans la réalisation du travail de ce séminaire.

- [Séance d'introduction au travail](slides/index.html): lors de cette séance, nous discutons l'objectif du projet, sa structure, les échéances de remises intermédiaires et finales ainsi que de consignes encadrant la réalisation du projet (utilisation d'IA, méthode de récolte de données,application, etc.)

- [Introduction à `R` et *Rstudio*](R_intro/intro_R.html): Ce chapitre introduit `R` et son environnement *RStudio*, en présentant l'interface et la notion de librairie. Il enseigne ensuite le Tidyverse et son *pipe* `%>%`, qui permet de manipuler des données de façon lisible via des fonctions comme filter(), mutate() ou group_by(). Il couvre la régression linéaire OLS avec lm() et montre comment estimer et interpréter un modèle. Enfin, `ggplot2` est introduit, expliquant comment produire des visualisations (nuages de points, boxplots, histogrammes) en combinant couches graphiques et transformations de données.