---
title: "Introduction à R"
format: html
editor: visual
---

Dans le cadre du séminaire, les étudiant$\cdot$es seront amené$\cdot$es
à employer des méthodes économétrique afin d'analyser des données et
déterminer si l'on peut observer une discrimination sur un segment de
marché. Ceci nécessite de recourir à un langage de programmation
statistique, à un environnement de programmation et à des librairies.
L'objectif de ce parcours est d'expliquer ce que cela signifie et
d'introduire les étudiant$\cdot$es à leur utilisation.

## Un langage de programmation

Un langage de programmation est un outil qui nous permet de communiquer
avec un ordinateur afin de lui faire exécuter des tâches. Il existe
divers langages de programmation conçus selon les objectifs dressés. Dans notre
cas, nous souhaitons exécuter des opérations mathématiques et
statistiques: nous nous orienterons donc vers un langage de
programmation à tel but. Ces langages de programmation permettent donc de traiter des données et de produire des statistiques descriptives, des graphiques, des cartes et bien sûr des régressions.

Parmi l'ensemble des langages, `R` présente plusieurs avantages:

* `R` est un langage *open-soure*. Le logiciel est gratuit et quiconque peut disposer du code afin de l'améliorer ou d'en proposer des variantes. 
* `R` présente une importante communauté d'utilisateur$\cdot$ices qui contribue à la résolution de problème et à l'évolution du langage. 
* La littérature économétrique contribue fréquemment à l'intégration de nouvelles méthodes à`R`. Les techniques économétriques de pointes y sont généralement accessibles.

Ces contributions sont faites sous forme de librairies : des fonctions pré-faites qui permettent **(i)** de simplifier l'usage de `R` et **(ii)** de réaliser des tâches complexes.

## Une librairie

Le langage de programmation `R` est utilisable avec un ensemble de fonction que l'on appelle ** base functions**. Ces fonctions de base permettent de réaliser des opérations fondamentales. Lorsque l'on

```{r}
data(mtcars)

```
















